---
- name: Run inspect
  hosts: all
  gather_facts: no
  vars:
    namespace: "{{ ansible_eda.event.resource.metadata.namespace }}"
  tasks:
  - name: run must-gather
    shell: oc adm inspect ns/"{{ namespace }}" 